### ISSUE TITLE
App is crashing MessageQueue-JNI: java.lang.NullPointerException

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#19]
Hello

My cometchat app is crashing on startup. Please look into it

MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'java.lang.String models.Contact.cometid' on a null object reference
                                                                    at activities.CCSingleChatActivity$4.afterTextChanged(SourceFile:522)
                                                                    at android.widget.TextView.sendAfterTextChanged(TextView.java:8203)
                                                                    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10382)
                                                                    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
                                                                    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
                                                                    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
                                                                    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
                                                                    at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:223)
                                                                    at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
                                                                    at android.widget.TextView.doKeyDown(TextView.java:6285)
                                                                    at android.widget.TextView.onKeyDown(TextView.java:6075)
                                                                    at android.view.KeyEvent.dispatch(KeyEvent.java:2688)
                                                                    at android.view.View.dispatchKeyEvent(View.java:9960)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1630)
                                                                    at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:405)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1798)
                                                                    at android.app.Activity.dispatchKeyEvent(Activity.java:3021)
                                                                    at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                                                                    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                                                                    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                                                                    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                                                                    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                                                                    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                                                                	at android.view.inputmethod.InputMethodManager.finishedInputEvent(In

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

We are investigating this issue at our end we will provide you with the solution shortly. In the meanwhile, it would be great if you can provide us with the CometChat SDK version you are using along with exact steps to reproduce the above crash. 

Thank You

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
Here is the steps how I am getting this issue

As I want to customize the UI of cometchat, I decided to choose one option of using UI module from this documentation site. [https://developer.cometchat.com/docs/android-advanced]()

Then I downloaded UI source code for here [https://secure.cometchat.com/licenses/sdk/51850](url)
and implemented module in my project .

Now when I start chat activity from my app it starts crashing within 1 or 2 seconds.
There is not any other steps involved in this bug as it stops on starting chat
