### ISSUE TITLE
App crashed with java.lang.IllegalArgumentException: Non-positive period.

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#28]
Hello,
My app is crashing on the click of reply button from chat notification with the following error.
java.lang.IllegalArgumentException: Non-positive period.
I am not able to find any solution. Please help me

```
FATAL EXCEPTION: IntentService[DirectReplyService]
                                                              Process: com.myheyhey, PID: 27604
                                                              java.lang.IllegalArgumentException: Non-positive period.
                                                                  at java.util.Timer.scheduleAtFixedRate(Timer.java:327)
                                                                  at com.inscripts.heartbeats.CCHeartbeat.startHeartbeat(SourceFile:164)
                                                                  at com.inscripts.heartbeats.CCHeartbeat.changeHybridHeartbeatInverval(SourceFile:184)
                                                                  at cometchat.inscripts.com.cometchatcore.coresdk.CometChat.resetOneOnOneHeartbeatInterval(SourceFile:1070)
                                                                  at cometchat.inscripts.com.cometchatcore.coresdk.CometChat.sendMessage(SourceFile:3032)
                                                                  at services.DirectReplyService.onHandleIntent(SourceFile:110)
                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                  at android.os.Looper.loop(Looper.java:203)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mehtanishant** [comment]
Hello @imdBhargav,

We have tried replicating the issue at our end, however, the crash is not happening at our end. Kindly let us know the SDK version you are using so that we can check accordingly. Also, we recommend using the latest Android SDK v7.29.0 in your project.

We appreciate your time and patience.

Thank you
