### ISSUE TITLE
Crashing while launch chat

### ISSUE THREAD

**Issue by pjadhav138** [cometchat-go/android-chat-sdk-demo#30]
This is an error log getting  

 java.lang.NoSuchFieldError: No static field tabs of type I in class Lcometchat/inscripts/com/readyui/R$id; or its superclasses (declaration of 'cometchat.inscripts.com.readyui.R$id' appears in /data/app/com.evolutionco.copal-hYajAUoMSZyC0mc9pxWoDQ==/split_lib_slice_3_apk.apk)
        at activities.CometChatActivity.setupFields(SourceFile:745)
        at activities.CometChatActivity.onCreate(SourceFile:165)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-03-27 11:14:01.952 25254-25254/com.evolutionco.copal E/memtrack: Couldn't load memtrack module

**Comment by mehtanishant** [comment]
Hello @pjadhav138 ,

As per the error logs, it seems that there is a duplicate id tabs in one of your layouts or the XML file name that is getting conflicted with the CometChat layout file. We suggest renaming the view id or the XML file entirely. This should resolve the error.

You can also book a remote session from the below URL if the error still exists:
https://www.cometchat.com/schedule-session

Thank you.
