### ISSUE TITLE
Application gets crash :  java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#7]
On Random basis, Comet chat Activity gets crash on opening with the following error

FATAL EXCEPTION: TokenRefresher
    java.lang.NoSuchFieldError: No field PREFER_HIGHEST_OR_REMOTE_VERSION_NO_FORCE_STAGING of type Lcom/google/android/gms/dynamite/DynamiteModule$VersionPolicy; in class Lcom/google/android/gms/dynamite/DynamiteModule; or its superclasses (declaration of 'com.google.android.gms.dynamite.DynamiteModule' appears in /data/app/com.myheyhey-2/base.apk:classes89.dex)
    at com.google.android.gms.flags.FlagValueProvider.initialize(Unknown Source)
    at com.google.android.gms.flags.FlagRegistry.initialize(Unknown Source)
    at com.google.firebase.auth.internal.zzw.initialize(Unknown Source)
    at com.google.firebase.auth.internal.zzs.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)

As per my assumptions, crash happens, When comet chat receives a push notification.
And after push notification, When I open the app normally(Not by clicking on push notification), it gets crash.

**Comment by jitvarpatil** [comment]
Hello,

The issue you are facing is because of firebase dependency conflicts. You can refer our troubleshooting guide at the following link:

 https://help.cometchat.com/faqs-and-troubleshooting/android/firebase-dependency-conflict/

If this doesn't solve the issue you are facing you can book a session with us using the below link 

https://www.cometchat.com/schedule-session/
